name: Experimental Cycle

on:
  release:
    types: [published]

jobs:

  experimental:

    runs-on: windows-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    steps:
      - name: Get Build Version
        id: build
        run: |
          $BUILD_VERSION = [regex]::split($env:GITHUB_REF, "v(.*)")[1]
          Write-Output "BUILD_VERSION=$BUILD_VERSION" >> $env:GITHUB_ENV
          Write-Host "v$BUILD_VERSION"

      - name: Show Build Version
        run: |
          Write-Host $env:BUILD_VERSION
          Write-Host ${{ env.BUILD_VERSION }}