name: Publish InfoPhoenix

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  SOLUTION: ".\\InfoPhoenix.sln"
  PUBLISH_PROJECT: ".\\src\\Nameless.InfoPhoenix.Client\\Nameless.InfoPhoenix.Client.csproj"
  PUBLISH_PATH: ".\\publish\\"
  ARTIFACTS_PATH: ".\\artifacts\\"

jobs:
  publishing:
    runs-on: windows-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Add GitHub Package Registry As NuGet Source
        run: >
          dotnet nuget add source
          --username ${{ github.repository_owner }}
          --password ${{ secrets.GITHUB_TOKEN }}
          --store-password-in-clear-text
          --name github ${{ vars.PACKAGE_SOURCE_URL_GITHUB }}

      - name: Get Version From Revision Tag
        shell: pwsh
        run: |
          $tag = "${{ github.ref_name }}"
          if ($tag -match '^v(\d+\.\d+\.\d+)$') {
            echo "VERSION=$($matches[1])" >> $env:GITHUB_ENV
            echo "Publishing version: $($matches[1])"
          } else {
            echo "VERSION=1.0.0" >> $env:GITHUB_ENV
            echo "Publishing version: 1.0.0"
          }          

      - name: Checkout Source Code
        uses: actions/checkout@v4.2.2

      - name: Publish InfoPhoenix
        run: >
          dotnet publish $env:PUBLISH_PROJECT
          -p:AssemblyVersion=$env:VERSION
          -p:FileVersion=$env:VERSION
          -p:Version=$env:VERSION
          --configuration Release
          --self-contained
          --output $env:PUBLISH_PATH
          --artifacts-path $env:ARTIFACTS_PATH
          --verbosity normal

      - name: Compress Output Files
        shell: pwsh
        run: Compress-Archive -Path $env:PUBLISH_PATH -DestinationPath "InfoPhoenix.v$($env:VERSION).zip"

      - name: Upload Publish Assets
        uses: softprops/action-gh-release@v2.2.0
        with:
          files: "InfoPhoenix.v${{ env.VERSION }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
