name: Publish Cycle

on:
  push:
    tags:
      - "v*.*.*"

env:
  OUTPUT_PATH: './release'

jobs:

  publishing:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x']

    steps:
      - name: Get Build Version
        id: build
        run: |
          if [[ ${GITHUB_REF} =~ \/v(.*)$ ]]
          then
            echo version=${BASH_REMATCH[1]} >> $GITHUB_OUTPUT
          else
            echo version='1.0.0' >> $GITHUB_OUTPUT
          fi

      - name: Checkout Source Code
        uses: actions/checkout@v4.1.6

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Setup GitHub Package Registry for NuGet
        run: |
          dotnet nuget add source \
          --username ${{ github.repository_owner }} \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text \
          --name github ${{ vars.NUGET_SOURCE_URL }}

      - name: Restore Solution
        run: dotnet restore ./Release.sln

      - name: Build Solution => Release
        if: success()
        run: |
          dotnet build ./Release.sln \
          -p:Version=${{ steps.build.outputs.version }} \
          --output ${{ env.OUTPUT_PATH }} \
          --configuration Release \
          --no-restore \
          --self-contained \
          --verbosity normal

      - name: Compress Files
        if: success()
        run: cd ${{ env.OUTPUT_PATH }}; zip -r -9 ../v${{ steps.build.outputs.version }}.zip *; cd ..
      
      - name: Publish release
        uses: softprops/action-gh-release@v2.0.5
        if: success()
        with:
          files: v${{ steps.build.outputs.version }}.zip